In [1]:
import numpy as np
import pandas as pd
import csv

In [2]:
df=pd.read_csv("train_1.csv",header=None)
data=df.values
print(data)

[[0 0 0 0]
 [0 1 0 1]
 [1 0 0 1]
 [1 1 0 0]
 [0 0 1 1]
 [0 1 1 0]
 [1 0 1 0]
 [1 1 1 1]]


In [3]:
X_train=data[:,0:3].T
Y_train=data[:,3]
shape_X = X_train.shape
shape_Y = Y_train.shape
m = X_train.shape[1]
print(shape_X,shape_Y,m)

(3, 8) (8,) 8


In [4]:
def sigmoid(z):
    s = 1 / (1 + np.exp(-z))    
    return s

In [5]:
def forward_propagation(X, parameters):
    W1 = parameters["W1"]
    b1 = parameters["b1"]
    W2 = parameters["W2"]
    b2 = parameters["b2"]

    Z1 = np.dot(W1,X)+b1
    A1 = np.tanh(Z1)
    Z2 = np.dot(W2,A1)+b2
    A2 = sigmoid(Z2)
    
    assert(A2.shape == (1, X.shape[1]))
    
    cache = {"Z1": Z1,
             "A1": A1,
             "Z2": Z2,
             "A2": A2}
    
    return A2, cache

In [6]:
def compute_cost(A2, Y, parameters):

    #m = Y.shape[1] 
    
    logprobs = np.multiply(Y,np.log(A2))+np.multiply(1-Y,np.log(1-A2))
    cost = (-1/m)*np.sum(logprobs)
    
    cost = np.squeeze(cost)  
    
    assert(isinstance(cost, float))
    
    return cost

In [7]:
def backward_propagation(parameters, cache, X, Y):

    m = X.shape[1]

    W1 = parameters["W1"]
    W2 = parameters["W2"]

    A1 = cache['A1']
    A2 = cache['A2']

    dZ2 = A2-Y
    dW2 = 1/m*np.dot(dZ2,A1.T)
    db2 = 1/m*np.sum(dZ2,axis=1,keepdims=True)
    dZ1 = np.dot(W2.T,dZ2)*(1-np.power(A1,2))
    dW1 = 1/m*np.dot(dZ1,X.T)
    db1 = 1/m*np.sum(dZ1,axis=1,keepdims=True)
    
    grads = {"dW1": dW1,
             "db1": db1,
             "dW2": dW2,
             "db2": db2}
    
    return grads

In [8]:
def update_parameters(parameters, grads, learning_rate = 5):

    W1 = parameters["W1"]
    b1 = parameters["b1"]
    W2 = parameters["W2"]
    b2 = parameters["b2"]

    dW1 = grads['dW1']
    db1 = grads['db1']
    dW2 = grads['dW2']
    db2 = grads['db2']

    W1 -= learning_rate*dW1
    b1 -= learning_rate*db1
    W2 -= learning_rate*dW2
    b2 -= learning_rate*db2

    parameters = {"W1": W1,
                  "b1": b1,
                  "W2": W2,
                  "b2": b2}
    
    return parameters

In [12]:
def model(X,Y,iterations=1000000):
    
    n_x=3
    n_h=10
    n_y=1
    
    W1 = np.random.randn(n_h,n_x)*0.01
    b1 = np.zeros((n_h,1))
    W2 = np.random.randn(n_y,n_h)*0.01
    b2 = np.zeros((n_y,1))
    #print(W1,W2)
    parameters = {"W1": W1,"b1": b1,"W2": W2,"b2": b2}

    for i in range(0, iterations):
        A2, cache = forward_propagation(X,parameters)
        
        cost = compute_cost(A2,Y,parameters)
 
        grads = backward_propagation(parameters,cache,X,Y)
 
        parameters = update_parameters(parameters, grads)
        if i%10000==0:
            print(cost)

    return parameters

In [13]:
parameters=model(X_train,Y_train)
print(parameters)

0.693147184893
0.693147064881
4.18063864596e-05
1.98743400379e-05
1.30616441896e-05
9.73091674928e-06
7.75408671781e-06
6.44458020949e-06
5.513142051e-06
4.81665435129e-06
4.27616672676e-06
3.84454814994e-06
3.49191994296e-06
3.19842184444e-06
2.95033700968e-06
2.73788674472e-06
2.55391168747e-06
2.39304976806e-06
2.25120550051e-06
2.12519685435e-06
2.01251403845e-06
1.9111508911e-06
1.81948459619e-06
1.73618830144e-06
1.66016659615e-06
1.59050716358e-06
1.52644406547e-06
1.46732952185e-06
1.4126119754e-06
1.36181886843e-06
1.31454299012e-06
1.27043156097e-06
1.22917743393e-06
1.19051194878e-06
1.15419908859e-06
1.12003066882e-06
1.08782235333e-06


KeyboardInterrupt: 

In [11]:
def predict(parameters, X):

    A2, cache = forward_propagation(X,parameters)
    predictions = np.round(A2)
    
    return predictions

print(predict(parameters,X_train))

[[ 0.  1.  1.  0.  1.  0.  0.  1.]]
