In [1]:
import numpy as np
import pandas as pd
import csv

In [2]:
df=pd.read_csv("train_1.csv",header=None)
data=df.values
print(data)

[[0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 1 1]
 [0 0 1 0 0 1 0 2]
 [0 0 1 1 0 1 1 3]
 [0 1 0 0 0 0 1 1]
 [0 1 0 1 0 0 0 0]
 [0 1 1 0 0 1 1 3]
 [0 1 1 1 0 1 0 2]
 [1 0 0 0 0 1 0 2]
 [1 0 0 1 0 1 1 3]
 [1 0 1 0 0 0 0 0]
 [1 0 1 1 0 0 1 1]
 [1 1 0 0 0 1 1 3]
 [1 1 0 1 0 1 0 2]
 [1 1 1 0 0 0 1 1]
 [1 1 1 1 0 0 0 0]
 [0 0 0 0 1 1 1 3]
 [0 0 0 1 1 1 0 2]
 [0 0 1 0 1 0 1 1]
 [0 0 1 1 1 0 0 0]
 [0 1 0 0 1 0 1 1]
 [0 1 0 1 1 1 1 3]
 [0 1 1 0 1 0 0 0]
 [0 1 1 1 1 1 0 2]
 [1 0 0 0 1 0 1 1]
 [1 0 0 1 1 0 0 0]
 [1 0 1 0 1 1 1 3]
 [1 0 1 1 1 1 0 2]
 [1 1 0 0 1 0 0 0]
 [1 1 0 1 1 0 1 1]
 [1 1 1 0 1 1 0 2]
 [1 1 1 1 1 1 1 3]]


In [26]:
X_train=data[:,0:5].T
Y_train=data[:,5:7].T
shape_X = X_train.shape
shape_Y = Y_train.shape
m = X_train.shape[1]
print(shape_X,shape_Y,m)

(5, 32) (2, 32) 32


In [27]:
def sigmoid(z):
    s = 1 / (1 + np.exp(-z))    
    return s

In [28]:
def forward_propagation(X, parameters):
    W1 = parameters["W1"]
    b1 = parameters["b1"]
    W2 = parameters["W2"]
    b2 = parameters["b2"]

    Z1 = np.dot(W1,X)+b1
    A1 = np.tanh(Z1)
    Z2 = np.dot(W2,A1)+b2
    A2 = sigmoid(Z2)
    
    assert(A2.shape == (2, X.shape[1]))
    
    cache = {"Z1": Z1,
             "A1": A1,
             "Z2": Z2,
             "A2": A2}
    
    return A2, cache

In [29]:
def compute_cost(A2, Y, parameters):

    #m = Y.shape[1] 
    
    logprobs = np.multiply(Y,np.log(A2))+np.multiply(1-Y,np.log(1-A2))
    cost = (-1/m)*np.sum(logprobs)
    
    cost = np.squeeze(cost)  
    
    
    
    assert(isinstance(cost, float))
    
    return cost

In [30]:
def backward_propagation(parameters, cache, X, Y):

    m = X.shape[1]

    W1 = parameters["W1"]
    W2 = parameters["W2"]

    A1 = cache['A1']
    A2 = cache['A2']

    dZ2 = A2-Y
    dW2 = 1/m*np.dot(dZ2,A1.T)
    db2 = 1/m*np.sum(dZ2,axis=1,keepdims=True)
    dZ1 = np.dot(W2.T,dZ2)*(1-np.power(A1,2))
    dW1 = 1/m*np.dot(dZ1,X.T)
    db1 = 1/m*np.sum(dZ1,axis=1,keepdims=True)
    
    grads = {"dW1": dW1,
             "db1": db1,
             "dW2": dW2,
             "db2": db2}
    
    return grads

In [34]:
def update_parameters(parameters, grads, learning_rate = 1):

    W1 = parameters["W1"]
    b1 = parameters["b1"]
    W2 = parameters["W2"]
    b2 = parameters["b2"]

    dW1 = grads['dW1']
    db1 = grads['db1']
    dW2 = grads['dW2']
    db2 = grads['db2']

    W1 -= learning_rate*dW1
    b1 -= learning_rate*db1
    W2 -= learning_rate*dW2
    b2 -= learning_rate*db2

    parameters = {"W1": W1,
                  "b1": b1,
                  "W2": W2,
                  "b2": b2}
    
    return parameters

In [35]:
def model(X,Y,iterations=100000):
    
    n_x=5
    n_h=10
    n_y=2
    
    W1 = np.random.randn(n_h,n_x)*0.01
    b1 = np.zeros((n_h,1))
    W2 = np.random.randn(n_y,n_h)*0.01
    b2 = np.zeros((n_y,1))
    #print(W1,W2)
    parameters = {"W1": W1,"b1": b1,"W2": W2,"b2": b2}

    for i in range(0, iterations):
        A2, cache = forward_propagation(X,parameters)
        
        cost = compute_cost(A2,Y,parameters)
 
        grads = backward_propagation(parameters,cache,X,Y)
 
        parameters = update_parameters(parameters, grads)
        if i%10000==0:
            print(cost)

    return parameters

In [36]:
parameters=model(X_train,Y_train)
print(parameters)

1.38630020574
0.000810613969062
0.000401141585055
0.000266995202006
0.00020017626613
0.000160118550404
0.000133406642858
0.000114312406395
9.99776429025e-05
8.88164403663e-05
{'W1': array([[-5.74464761,  0.23376755, -0.17559342, -4.93337487,  3.68997696],
       [-2.44792862,  0.58921183,  3.17871164, -0.38841339,  1.89605075],
       [-4.57811784, -2.04154332,  6.0305478 ,  0.26995798,  4.59936261],
       [-2.09511341, -0.15262131,  2.16324892,  0.96810645,  2.57758414],
       [-0.12593803,  3.93068358, -0.11579841,  4.28491175, -4.19013922],
       [ 2.88484177,  0.84927627, -3.4203899 ,  0.50314363,  3.56176317],
       [ 0.27003609, -2.83618354, -0.47925289,  2.50978383, -4.2112401 ],
       [-1.77729184,  0.33293607,  2.07378859,  0.6238558 ,  2.55403615],
       [-0.09376878, -3.82482508,  0.17056932, -3.10108649, -2.68383616],
       [ 1.43518128,  3.78935729, -1.13691966, -4.12014614,  1.74826945]]), 'b1': array([[-1.4433611 ],
       [-3.95577543],
       [-2.44634982],
    

In [39]:
def predict(parameters, X):

    A2, cache = forward_propagation(X,parameters)
    predictions = np.round(A2)
    
    return predictions.T

print(predict(parameters,X_train))

[[ 0.  0.]
 [ 0.  1.]
 [ 1.  0.]
 [ 1.  1.]
 [ 0.  1.]
 [ 0.  0.]
 [ 1.  1.]
 [ 1.  0.]
 [ 1.  0.]
 [ 1.  1.]
 [ 0.  0.]
 [ 0.  1.]
 [ 1.  1.]
 [ 1.  0.]
 [ 0.  1.]
 [ 0.  0.]
 [ 1.  1.]
 [ 1.  0.]
 [ 0.  1.]
 [ 0.  0.]
 [ 0.  1.]
 [ 1.  1.]
 [ 0.  0.]
 [ 1.  0.]
 [ 0.  1.]
 [ 0.  0.]
 [ 1.  1.]
 [ 1.  0.]
 [ 0.  0.]
 [ 0.  1.]
 [ 1.  0.]
 [ 1.  1.]]
